version: '3.4'

services:
  sqldata:
    image: microsoft/mssql-server-windows-developer 
    environment:
     - ACCEPT_EULA=Y
     - sa_password=!23qweASD
    ports:
     - '51433:1433'
  lms.ui:
    image: ${DOCKER_REGISTRY-}lmsui
    build:
      context: .
      dockerfile: LMS.UI\Dockerfile